spring.application.name=calculator_project
spring.datasource.url=jdbc:postgresql://localhost:5432/caldatabase
spring.datasource.username=postgres
spring.datasource.password=Coder#098
spring.jpa.hibernate.ddl-auto=update